# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D133z9HggyOXlo9BcAnG9Mp4OU6Prcwd
"""

import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
import warnings
warnings.filterwarnings("ignore")

titanic = sns.load_dataset('titanic')
df = titanic[['pclass', 'sex', 'age', 'survived']].dropna()

df.head()

df.describe()

numeric = df.select_dtypes(include=np.number)
corr = numeric.corr()
mask = np.triu(np.ones_like(corr, dtype=bool))
sns.heatmap(corr,annot=True,fmt=".2f" ,cmap='YlGnBu', vmin=-1, vmax=1)
plt.title('Correlation matrix (numeric features)')
plt.show()

df["survived"].value_counts()

sns.countplot(x=df['survived'], hue=df['pclass'])

df["sex"]



sns.countplot(x=df['sex'], hue=df['survived'])

df.groupby('sex')[['survived']].mean()

X = df.drop('survived', axis=1)
y = df['survived']

ct = ColumnTransformer([
    ('encoder', OneHotEncoder(drop='first'), ['sex'])
], remainder='passthrough')

X = ct.fit_transform(X)

sc = StandardScaler()
X = sc.fit_transform(X)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = Sequential([
    Dense(6, activation='relu', input_dim=X_train.shape[1]),
    Dense(4, activation='relu'),
    Dense(1, activation='sigmoid')
])

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
model.fit(X_train, y_train, epochs=50, batch_size=16, verbose=0)

loss, acc = model.evaluate(X_test, y_test, verbose=0)
print(f"\nModel trained successfully with Accuracy: {acc*100:.2f}%")

print("\n===== Titanic Survival Prediction using ANN =====")
pclass = int(input("Enter Passenger Class (1 = First, 2 = Second, 3 = Third): "))
age = float(input("Enter Age: "))
gender = input("Enter Gender (male/female): ").strip().lower()
sex_male = 1 if gender == 'male' else 0
user_data = np.array([[sex_male, pclass, age]])
user_data_scaled = sc.transform(user_data)
prediction = model.predict(user_data_scaled)[0][0]
print("\nPrediction Result:")
if prediction > 0.5:
    print(f" The passenger would have SURVIVED! (Survival Chance: {prediction*100:.2f}%)")
else:
    print(f" The passenger would NOT have survived. (Survival Chance: {prediction*100:.2f}%)")